"""LaTeX exports for the manuscript tables."""

from __future__ import annotations

import math
import re
from pathlib import Path
from typing import Mapping

import pandas as pd


def latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
        "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def format_bf(value: float) -> str:
    if not math.isfinite(value):
        return "--"
    if abs(value) >= 1_000:
        exponent = int(math.floor(math.log10(abs(value))))
        return rf"${value / 10 ** exponent:.2f}\times 10^{{{exponent}}}$"
    return f"{value:.3f}"


def results_latex(frame: pd.DataFrame) -> str:
    """Create the includeable table body used by the main/appendix result tables."""
    lines = [r"% generated by aerobat.analysis.tables", r"\begin{longtable}{llrrrrrrrrl}", r"\toprule", r"$Y$ & $X$ & $|D_h|$ & $B$ & $J$ & $T$ & $n$ & $\mathrm{BF}_{10}$ & $\Delta$ & $\tau$ & Class \\", r"\midrule"]
    symbols = {
        "Positive": "$+$",
        "Negative": "$-$",
        "No effect": "$0$",
        "Inconclusive": r"$\oslash$",
        "positive": "$+$",
        "negative": "$-$",
        "no_effect": "$0$",
        "inconclusive": r"$\oslash$",
        "direction_unresolved": r"$\oslash$",
    }
    for row in frame.itertuples(index=False):
        lines.append(
            f"{latex_escape(row.behavior_name)} & {latex_escape(row.variable)} & {int(row.D_h)} & {int(row.B)} & {int(row.J)} & {int(row.T)} & {int(row.n)} & {format_bf(float(row.bf10))} & {float(row.Delta):.3f} & {float(row.tau):.3f} & {symbols.get(row.effect_class, row.effect_class)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}"])
    return "\n".join(lines) + "\n"


def write_results_latex(frame: pd.DataFrame, path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(results_latex(frame), encoding="utf-8")
    return target


EFFECT_LABELS = {
    "Positive": "$+$",
    "Negative": "$-$",
    "No effect": "$0$",
    "Inconclusive": r"$\oslash$",
    "positive": "$+$",
    "negative": "$-$",
    "no_effect": "$0$",
    "inconclusive": r"$\oslash$",
    "direction_unresolved": r"$\oslash$",
}

COMPACT_LABEL_REPLACEMENTS = [
    ("communication", "comm."),
    ("authority", "auth."),
    ("context", "ctx."),
    ("information", "info."),
    ("instruction", "instr."),
    ("relative", "rel."),
    ("resource", "res."),
    ("resources", "res."),
]

MANIPULATED_COMPONENT_LABELS = {
    "objective": r"${f}$.\textit{roles}",
    "authority": r"${f}$.\textit{authority}",
    "constraints": r"${f}$.\textit{constraints}",
    "situational context": r"${f}$.\textit{world.context}",
    "resource": r"${f}$.\textit{world.resource}",
    "actor": r"${f}$.\textit{world.actors}",
    "risk & return": r"${f}$.\textit{consequence}",
}

PER_EVIDENCE_CLASS_CAPTION = (
    "Full per-evidence-class statistical analytic result across target behaviors "
    "and hypothesized causal variables. Design columns report domains, instantiated "
    "matched groups, causal variable values, and rounds. Abbreviations: auth. = "
    "authority, comm. = communication, ctx. = context, info. = information, "
    r"instr. = instruction, rel. = relative, res. = resource; $\oslash$ = "
    r"inconclusive effect; $0$ = no effect."
)


def _is_missing(value: object) -> bool:
    return pd.isna(value)


def _label_text(value: object) -> str:
    text = "" if _is_missing(value) else str(value)
    return " ".join(text.replace("_", " ").replace("-", " ").split())


def _pretty_label(value: object) -> str:
    return latex_escape(_label_text(value))


def _compact_label_text(value: object) -> str:
    text = _label_text(value)
    for term, replacement in COMPACT_LABEL_REPLACEMENTS:
        pattern = rf"\b{re.escape(term)}\b"

        def replace(match: re.Match[str]) -> str:
            if match.group(0)[:1].isupper():
                return replacement[:1].upper() + replacement[1:]
            return replacement

        text = re.sub(pattern, replace, text, flags=re.IGNORECASE)
    return text


def _compact_label(value: object) -> str:
    return latex_escape(_compact_label_text(value))


def _compact_label_words(value: object) -> list[str]:
    return [latex_escape(word) for word in _compact_label_text(value).split()]


def _bold_latex(value: str) -> str:
    return rf"\textbf{{{value}}}" if value else ""


def _behavior_label_lines(value: object) -> list[str]:
    text = _label_text(value).lower()
    if text == "deceive":
        return [_bold_latex("deception")]
    if text == "literal instruction following":
        return [_bold_latex("literalism")]
    if text == "strategic aggression":
        return [_bold_latex("strategic"), _bold_latex("aggression")]
    if text == "non compliance":
        return [_bold_latex("non"), _bold_latex("compliance")]
    return [_bold_latex(_pretty_label(value))]


def _manipulated_component_label(value: object) -> str:
    if _is_missing(value):
        return "--"
    key = str(value).strip().lower()
    return MANIPULATED_COMPONENT_LABELS.get(key, _pretty_label(value))


def _format_decimal(value: object, digits: int = 3) -> str:
    if _is_missing(value):
        return "--"
    return f"{float(value):.{digits}f}"


def _format_int(value: object) -> str:
    if _is_missing(value):
        return "--"
    return str(int(value))


def _format_p(value: object) -> str:
    if _is_missing(value):
        return "--"
    value = float(value)
    if value < 0.001:
        return r"$<.001$"
    return f"{value:.3f}"


def _format_table_bf(value: object) -> str:
    if _is_missing(value):
        return "--"
    value = float(value)
    if value == 0:
        return "0"
    if abs(value) >= 1000:
        exponent = int(math.floor(math.log10(abs(value))))
        mantissa = value / (10**exponent)
        return rf"${mantissa:.1f}e{exponent}$"
    if abs(value) < 0.001:
        return r"$<10^{-3}$"
    return f"{value:.3f}"


def _effect_label(value: object) -> str:
    return EFFECT_LABELS.get(str(value), _pretty_label(value))


def _latex_caption(value: str) -> str:
    parts = re.split(r"(\$[^$]*\$)", value)
    return "".join(part if part.startswith("$") else latex_escape(part) for part in parts)


def _evidence_class_result_rows(frame: pd.DataFrame) -> list[str]:
    lines = []
    previous_behavior = None
    previous_group = None
    behavior_lines: list[str] = []
    behavior_line_index = 0
    cause_words: list[str] = []
    cause_word_index = 0

    for row in frame.itertuples(index=False):
        behavior = row.behavior_name
        group = (row.behavior_name, row.variable)
        is_new_group = group != previous_group
        if behavior != previous_behavior:
            behavior_lines = _behavior_label_lines(behavior)
            behavior_line_index = 0
        if is_new_group:
            cause_words = _compact_label_words(row.variable)
            cause_word_index = 0

        behavior_cell = (
            behavior_lines[behavior_line_index]
            if behavior_line_index < len(behavior_lines)
            else ""
        )
        cause_cell = (
            cause_words[cause_word_index]
            if cause_word_index < len(cause_words)
            else ""
        )
        invariant_cells = [
            _manipulated_component_label(row.manipulated_component),
            _format_int(row.num_domains),
            _format_int(row.num_groups),
            _format_int(row.num_causal_values),
            _format_int(row.num_rounds),
        ]
        if not is_new_group:
            invariant_cells = [""] * len(invariant_cells)

        cells = [
            behavior_cell,
            cause_cell,
            *invariant_cells,
            _compact_label(row.outcome),
            _format_int(row.n),
            _format_table_bf(row.bf10),
            _format_decimal(row.Delta),
            _format_decimal(row.tau),
            _format_p(row.p_tau),
            _effect_label(row.effect_class),
        ]
        lines.append(" & ".join(cells) + r" \\")

        previous_behavior = behavior
        previous_group = group
        behavior_line_index += 1
        cause_word_index += 1
    return lines


def evidence_class_results_latex(
    frame: pd.DataFrame,
    *,
    caption: str = PER_EVIDENCE_CLASS_CAPTION,
    label: str = "tab:tabular-results-full",
) -> str:
    header = (
        r"Behavior $Y$ & Cause $X$ & Manipulated & $|D_h|$ & $\mathrm{B}$ & "
        r"$\mathrm{J}$ & $\mathrm{T}$ & Evidence class $c$ & $n$ & "
        r"$\mathrm{BF}_{10}$ & $\Delta$ & $\tau$ & $p_\tau$ & Effect \\"
    )
    lines = [
        r"% Generated by aerobat.analysis.tables; do not edit by hand.",
        r"% Parent manuscript requires: \usepackage{booktabs,longtable}",
        r"\begingroup",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{1.08}",
        r"\begin{longtable}{p{0.085\linewidth}p{0.100\linewidth}p{0.105\linewidth}rrrrlrrrrrl}",
        rf"\caption{{{_latex_caption(caption)}}}\label{{{label}}}\\",
        r"\toprule",
        header,
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        header,
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{14}{r}{Continued on next page} \\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    lines.extend(_evidence_class_result_rows(frame))
    lines.extend([r"\end{longtable}", r"\endgroup", ""])
    return "\n".join(lines)


def write_evidence_class_results_latex(frame: pd.DataFrame, path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(evidence_class_results_latex(frame), encoding="utf-8")
    return target


DEFAULT_PRIOR_SCALE = math.sqrt(2) / 2


def _effect_class_key(value: object) -> str:
    return str(value).strip().lower().replace(" ", "_")


def _closest_prior_scale(frame: pd.DataFrame, default_scale: float) -> float:
    scales = frame.prior_scale.dropna().drop_duplicates()
    if scales.empty:
        raise ValueError("Prior-sensitivity frame has no prior scales")
    return float(min(scales, key=lambda value: abs(float(value) - default_scale)))


def prior_sensitivity_table(
    frame: pd.DataFrame,
    *,
    default_scale: float = DEFAULT_PRIOR_SCALE,
) -> pd.DataFrame:
    """Return the Appendix E prior-sensitivity table data."""
    default = _closest_prior_scale(frame, default_scale)
    default_classes = (
        frame[frame.prior_scale == default][["behavior_name", "axis_slug", "effect_class"]]
        .rename(columns={"effect_class": "default_effect_class"})
        .drop_duplicates(["behavior_name", "axis_slug"])
    )
    scored = frame.merge(default_classes, on=["behavior_name", "axis_slug"], how="left")
    if scored.default_effect_class.isna().any():
        raise ValueError("Every hypothesis must have a default-prior classification")

    rows = []
    for scale, block in scored.groupby("prior_scale", sort=True):
        counts = block.effect_class.map(_effect_class_key).value_counts()
        rows.append(
            {
                "prior_scale": float(scale),
                "is_default": math.isclose(float(scale), default, rel_tol=1e-12, abs_tol=1e-12),
                "hypotheses": block[["behavior_name", "axis_slug"]].drop_duplicates().shape[0],
                "positive": int(counts.get("positive", 0)),
                "negative": int(counts.get("negative", 0)),
                "no_effect": int(counts.get("no_effect", 0)),
                "inconclusive": int(counts.get("inconclusive", 0)),
                "class_agreement": float(
                    block.effect_class.map(_effect_class_key).eq(
                        block.default_effect_class.map(_effect_class_key)
                    ).mean()
                ),
                "median_absolute_log10_shift": float(block.absolute_log10_shift.median()),
                "max_absolute_log10_shift": float(block.absolute_log10_shift.max()),
                "median_mcse": float(block.log10_bf10_mcse.median()),
                "max_mcse": float(block.log10_bf10_mcse.max()),
            }
        )
    return pd.DataFrame(rows)


def _prior_scale_label(scale: float, is_default: bool) -> str:
    if math.isclose(scale, DEFAULT_PRIOR_SCALE, rel_tol=1e-9, abs_tol=1e-9):
        suffix = r"^{\dagger}" if is_default else ""
        return rf"$\sqrt{{2}}/2 \approx {scale:.3f}{suffix}$"
    suffix = r"^{\dagger}" if is_default else ""
    return rf"${scale:.1f}{suffix}$"


def prior_sensitivity_latex(table: pd.DataFrame) -> str:
    """Create the includeable Appendix E prior-sensitivity table body."""
    lines = [
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"& \multicolumn{4}{c}{\textbf{Class counts}} & & \\",
        r"\cmidrule(lr){2-5}",
        r"\textbf{Prior scale $r$} & Pos. & Neg. & No eff. & Inconcl. & \textbf{Agree.} & \textbf{Med. $|\Delta\log_{10}\mathrm{BF}_{10}|$} \\",
        r"\midrule",
    ]
    for row in table.itertuples(index=False):
        shift = "---" if row.is_default else f"{row.median_absolute_log10_shift:.3f}"
        lines.append(
            f"{_prior_scale_label(float(row.prior_scale), bool(row.is_default))} & "
            f"{int(row.positive)} & {int(row.negative)} & {int(row.no_effect)} & "
            f"{int(row.inconclusive)} & {float(row.class_agreement):.2f} & {shift} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def write_prior_sensitivity_latex(table: pd.DataFrame, path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(prior_sensitivity_latex(table), encoding="utf-8")
    return target


def rubric_consistency_latex(frame: pd.DataFrame) -> str:
    lines = [
        r"\begin{tabular}{@{}lrrrrrrrrr@{}}",
        r"\toprule",
        r"\textbf{Behavior $Y$} & $|\mathcal{C}|$ & $n$ & $\bar r$ & $\bar r_{\text{res}}$ & alpha & $\lambda_1/|\mathcal{C}|$ & $r_{it}^{\min}$ & floor & null \\",
        r"\midrule",
    ]
    for row in frame.itertuples(index=False):
        lines.append(
            f"{latex_escape(row.target_behavior)} & {int(row.evidence_classes)} & {int(row.reviewed_runs)} & "
            f"{float(row.mean_interclass_spearman):.2f} & {float(row.residualized_mean_interclass_spearman):.2f} & "
            f"{float(row.cronbach_alpha):.2f} & {float(row.first_eigenvalue_share):.2f} & "
            f"{float(row.minimum_corrected_item_total_spearman):.2f} & {float(row.floor_rate):.2f} & {float(row.null_rate):.2f} \\\\"
        )
    lines.extend(
        [
            r"\midrule",
            f"\\textit{{mean}} & {frame.evidence_classes.mean():.1f} & {frame.reviewed_runs.mean():.0f} & "
            f"{frame.mean_interclass_spearman.mean():.2f} & {frame.residualized_mean_interclass_spearman.mean():.2f} & "
            f"{frame.cronbach_alpha.mean():.2f} & {frame.first_eigenvalue_share.mean():.2f} & "
            f"{frame.minimum_corrected_item_total_spearman.mean():.2f} & {frame.floor_rate.mean():.2f} & {frame.null_rate.mean():.2f} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
    )
    return "\n".join(lines) + "\n"


def write_rubric_consistency_latex(frame: pd.DataFrame, path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rubric_consistency_latex(frame), encoding="utf-8")
    return target


INTENSITY_TIERS = {
    0: ("no", "none", "never", "not", "without", "absent", "zero", "nothing", "lack", "lacks"),
    1: (
        "rare",
        "rarely",
        "isolated",
        "minimal",
        "minor",
        "slight",
        "weak",
        "brief",
        "single",
        "few",
        "seldom",
        "marginal",
        "incidental",
        "negligible",
    ),
    2: (
        "occasional",
        "occasionally",
        "sometimes",
        "some",
        "moderate",
        "moderately",
        "partial",
        "partially",
        "situational",
        "situationally",
        "intermittent",
        "selective",
        "selectively",
        "mixed",
        "limited",
    ),
    3: (
        "frequent",
        "frequently",
        "often",
        "regular",
        "regularly",
        "repeated",
        "repeatedly",
        "multiple",
        "recurring",
        "routinely",
        "broad",
        "broadly",
        "substantial",
        "strong",
    ),
    4: (
        "pervasive",
        "pervasively",
        "systematic",
        "systematically",
        "consistent",
        "consistently",
        "constant",
        "constantly",
        "always",
        "every",
        "all",
        "extensive",
        "extensively",
        "persistent",
        "persistently",
        "continuous",
        "continuously",
        "highly",
        "entirely",
        "thoroughly",
        "universally",
        "invariably",
    ),
}
INTENSITY_RANK = {
    word: tier for tier, words in INTENSITY_TIERS.items() for word in words
}
EXAMPLE_MARKER_RE = re.compile(r"e\.g\.|such as|including|\(")


def _max_intensity(text: object) -> float:
    hits = [
        INTENSITY_RANK[word.lower()]
        for word in re.findall(r"[A-Za-z]+", str(text))
        if word.lower() in INTENSITY_RANK
    ]
    return float(max(hits)) if hits else math.nan


def _spearman(left: pd.Series, right: pd.Series) -> float:
    valid = pd.DataFrame({"left": left, "right": right}).dropna()
    if valid.left.nunique() < 2 or valid.right.nunique() < 2:
        return math.nan
    return float(valid.left.corr(valid.right, method="spearman"))


def rubric_semantics_table(criteria: pd.DataFrame, pairs: pd.DataFrame) -> pd.DataFrame:
    """Return the behavior-level semantic table used by the appendix."""
    anchors = criteria.copy()
    anchors["words"] = anchors.criterion_text.astype(str).str.split().str.len()
    anchors["examples_per_anchor"] = anchors.criterion_text.astype(str).str.count(
        EXAMPLE_MARKER_RE
    )
    anchors["intensity"] = anchors.criterion_text.map(_max_intensity)

    rows = []
    for behavior, block in anchors.groupby("target_behavior", sort=True):
        behavior_pairs = pairs[
            (pairs.target_behavior_left == behavior)
            & (pairs.target_behavior_right == behavior)
        ]
        distinct = behavior_pairs[
            (behavior_pairs.evidence_class_left != behavior_pairs.evidence_class_right)
            & (behavior_pairs.level_score_left == behavior_pairs.level_score_right)
        ]
        level_pairs = behavior_pairs[
            behavior_pairs.evidence_class_left == behavior_pairs.evidence_class_right
        ]
        ladder = []
        for _evidence_class, class_block in block.groupby("evidence_class"):
            ladder.append(
                _spearman(class_block.level_score, class_block.intensity)
            )
        rows.append(
            {
                "target_behavior": behavior,
                "words": float(block.words.mean()),
                "examples_per_anchor": float(block.examples_per_anchor.mean()),
                "distinctiveness": float(distinct.cosine_similarity.mean()),
                "level_gradient_rho": _spearman(
                    level_pairs.level_distance, level_pairs.cosine_similarity
                ),
                "intensity_rho": float(pd.Series(ladder).mean()),
            }
        )
    return pd.DataFrame(rows)


def _format_signed(value: object) -> str:
    if _is_missing(value):
        return "--"
    return f"{float(value):+.2f}"


def rubric_semantics_latex(frame: pd.DataFrame) -> str:
    lines = [
        r"% generated by run_rubric_analysis.ipynb -- do not edit by hand",
        r"\begin{tabular}{@{}lrrrrr@{}}",
        r"\toprule",
        r"\textbf{Behavior $Y$} & words & examples & distinct. & level grad. & intensity $\rho$ \\",
        r"\midrule",
    ]
    for row in frame.itertuples(index=False):
        lines.append(
            f"{latex_escape(row.target_behavior)} & {float(row.words):.0f} & {float(row.examples_per_anchor):.2f} & "
            f"{float(row.distinctiveness):.2f} & {_format_signed(row.level_gradient_rho)} & {_format_signed(row.intensity_rho)} \\\\"
        )
    lines.extend(
        [
            r"\midrule",
            f"\\textit{{mean}} & {frame.words.mean():.0f} & {frame.examples_per_anchor.mean():.2f} & "
            f"{frame.distinctiveness.mean():.2f} & {frame.level_gradient_rho.mean():+.2f} & "
            f"{frame.intensity_rho.mean():+.2f} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
    )
    return "\n".join(lines) + "\n"


def write_rubric_semantics_latex(frame: pd.DataFrame, path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rubric_semantics_latex(frame), encoding="utf-8")
    return target


def rubric_sensitivity_latex(frame: pd.DataFrame) -> str:
    labels = {
        "available_case": r"available case (\textit{pipeline})",
        "complete_case": "complete cases only",
        "drop_most_null_class": "most-null class removed",
        "null_as_zero": r"nulls $\to$ level 0",
        "leave_one_out": r"leave one class out (all $K$)",
    }
    ordered = ["available_case", "complete_case", "drop_most_null_class", "null_as_zero"]
    lines = [
        r"% generated by run_rubric_analysis.ipynb -- do not edit by hand",
        r"\begin{tabular}{@{}lrrrrr@{}}",
        r"\toprule",
        r"\textbf{Construction of $\hat{y}_{ij}$} & $|H|$ & class agr. & $\mathrm{BF}_{10}$ agr. & $r_\Delta$ & sign flips \\",
        r"\midrule",
    ]
    indexed = frame.set_index("variant_family")
    for family in ordered:
        if family not in indexed.index:
            continue
        row = indexed.loc[family]
        lines.append(
            f"{labels[family]} & {int(row.hypotheses)} & {float(row.effect_class_agreement):.2f} & "
            f"{float(row.bf10_evidence_agreement):.2f} & {float(row.Delta_correlation):.3f} & {int(row.sign_flips)} \\\\"
        )
    if "leave_one_out" in indexed.index:
        row = indexed.loc["leave_one_out"]
        lines.extend(
            [
                r"\midrule",
                f"{labels['leave_one_out']} & {int(row.hypotheses)} & {float(row.effect_class_agreement):.2f} & "
                f"{float(row.bf10_evidence_agreement):.2f} & {float(row.Delta_correlation):.3f} & {int(row.sign_flips)} \\\\",
            ]
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def write_rubric_sensitivity_latex(frame: pd.DataFrame, path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rubric_sensitivity_latex(frame), encoding="utf-8")
    return target


GENERALIZATION_CAPTION = (
    "Full statistical analytic result across subject agent models. Abbreviations: "
    "auth. = authority, comm. = communication, ctx. = context, info. = information, "
    r"instr. = instruction, rel. = relative, res. = resource; $\oslash$ = "
    r"inconclusive effect; $0$ = no effect."
)


def _generalization_result_rows(frame: pd.DataFrame) -> list[str]:
    lines = []
    previous_behavior = None
    previous_group = None
    behavior_lines: list[str] = []
    behavior_line_index = 0

    for row in frame.itertuples(index=False):
        behavior = row.behavior_name
        group = (row.behavior_name, row.variable)
        is_new_group = group != previous_group
        if behavior != previous_behavior:
            behavior_lines = _behavior_label_lines(behavior)
            behavior_line_index = 0

        behavior_cell = (
            behavior_lines[behavior_line_index]
            if behavior_line_index < len(behavior_lines)
            else ""
        )
        cause_cell = _compact_label(row.variable) if is_new_group else ""
        manipulated_cell = (
            _manipulated_component_label(row.manipulated_component)
            if is_new_group
            else ""
        )
        cells = [
            behavior_cell,
            cause_cell,
            manipulated_cell,
            _pretty_label(row.alpha),
            _format_int(row.n),
            _format_table_bf(row.bf10),
            _format_decimal(row.Delta),
            _format_decimal(row.tau),
            _format_p(row.p_tau),
            _effect_label(row.effect_class),
        ]
        lines.append(" & ".join(cells) + r" \\")

        previous_behavior = behavior
        previous_group = group
        behavior_line_index += 1
    return lines


def inter_subject_generalization_latex(
    frame: pd.DataFrame,
    *,
    caption: str = GENERALIZATION_CAPTION,
    label: str = "tab:tabular-generalization",
) -> str:
    header = (
        r"Behavior $Y$ & Cause $X$ & Manipulated & $\alpha$ & $n$ & "
        r"$\mathrm{BF}_{10}$ & $\Delta$ & $\tau$ & $p_\tau$ & Effect \\"
    )
    lines = [
        r"% Generated by tabular_result_to_latex.ipynb; do not edit by hand.",
        r"% Parent manuscript requires: \usepackage{booktabs,longtable}",
        r"\begingroup",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{1.08}",
        r"\begin{longtable}{p{0.085\linewidth}p{0.18\linewidth}p{0.105\linewidth}p{0.115\linewidth}rrrrrl}",
        rf"\caption{{{_latex_caption(caption)}}}\label{{{label}}}\\",
        r"\toprule",
        header,
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        header,
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{10}{r}{Continued on next page} \\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    lines.extend(_generalization_result_rows(frame))
    lines.extend([r"\end{longtable}", r"\endgroup", ""])
    return "\n".join(lines)


def write_inter_subject_generalization_latex(frame: pd.DataFrame, path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(inter_subject_generalization_latex(frame), encoding="utf-8")
    return target


def _ratio(score: object, baseline: object) -> str:
    if _is_missing(score) or _is_missing(baseline) or float(baseline) == 0:
        return "--"
    return rf"$\times${float(score) / float(baseline):.1f}"


def environment_fidelity_latex(numbers: Mapping[str, object]) -> str:
    """Create the manuscript-format environment fidelity table."""
    task1_all = float(numbers["task1_exact_match_all"])
    task1_causal = float(numbers["task1_exact_match_causal"])
    task1_random_all = float(numbers["task1_random_match_all"])
    task1_random_causal = float(numbers["task1_random_match_causal"])
    task2_item = float(numbers["task2_item_accuracy_pct"]) / 100
    task2_group = float(numbers["task2_group_accuracy_pct"]) / 100
    task2_random_item = float(numbers["task2_random_baseline_pct"]) / 100
    task2_random_group = float(numbers["task2_group_random_baseline_pct"]) / 100
    task3_score = numbers.get("task3_human_eval_score")
    task3_score_text = "--" if _is_missing(task3_score) else rf"\textbf{{{float(task3_score):.3f}}}"
    lines = [
        r"\begin{table*}[!h]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{5pt}",
        r"\begin{tabular}{@{}llrrl@{}}",
        r"\toprule",
        r"\textbf{Evaluated unit} & \textbf{Metric} & $n$ & \textbf{Score} & \textbf{vs.\ chance} \\",
        r"\midrule",
        r"\multicolumn{5}{@{}l@{}}{\textbf{TASK 1: Variable value inference.}\quad $(F_{ij},\,V)\;\mapsto\;\hat{v}_{ij}$} \\",
        r"\multicolumn{5}{@{}l@{}}{\footnotesize\itshape recovering $v_{ij}$ from the configuration alone suggests $F_{ij}$ faithfully realizes its variable values} \\",
        r"\addlinespace[2pt]",
        rf"\quad all variables $V$ & exact match & {int(numbers['task1_n_variables'])} & \textbf{{{task1_all:.3f}}} & {_ratio(task1_all, task1_random_all)} \\",
        rf"\quad hypothesized cause $X$ only & exact match & {int(numbers['task1_n_causal_variables'])} & \textbf{{{task1_causal:.3f}}} & {_ratio(task1_causal, task1_random_causal)} \\",
        r"\addlinespace[2pt]\midrule",
        r"\multicolumn{5}{@{}l@{}}{\textbf{TASK 2: Config-to-simulation mapping.}\quad $\{(F_{ij},\ S_{i\phi(j)})\}_{j=1}^{\mathrm{J}} \mapsto \hat{\phi}$} \\",
        r"\multicolumn{5}{@{}l@{}}{\footnotesize\itshape matching masked simulations to their configurations suggests the level $x_j$ is what separates them} \\",
        r"\addlinespace[2pt]",
        rf"\quad configuration--simulation pair & accuracy & {int(numbers['task2_n_pairs'])}  & \textbf{{{task2_item:.3f}}} & {_ratio(task2_item, task2_random_item)} \\",
        rf"\quad whole matched group $i$ (all $\mathrm{{J}}$ correct) & accuracy & {int(numbers['task2_n_groups'])} & \textbf{{{task2_group:.3f}}} & {_ratio(task2_group, task2_random_group)} \\",
        r"\addlinespace[2pt]\midrule",
        r"\multicolumn{5}{@{}l@{}}{\textbf{TASK 3: Within-group variable inference.}\quad $\{(F_{ij},\,S_{ij})\}_{j=1}^{\mathrm{J}}\;\mapsto\;\hat{X}$} \\",
        r"\multicolumn{5}{@{}l@{}}{\footnotesize\itshape inferring $\hat{X}\approx X$ suggests no other variable dominates the within-group difference} \\",
        r"\addlinespace[2pt]",
        rf"\quad matched group $i$ & human $(\hat{{X}},X)$ match & {int(numbers.get('task3_n_groups', numbers['task2_n_groups']))} & {task3_score_text} & -- \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{\textbf{Fidelity estimation of the \texttt{AEROBAT}-generated environments.} \textbf{Chance} is computed from the actual answer space: for TASK 1 the expected exact-match rate of a guesser drawing uniformly from each variable's candidate values, and for TASK 2 that of a uniform random one-to-one map.}",
        r"\label{tab:fidelity}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


def write_environment_fidelity_latex(numbers: Mapping[str, object], path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(environment_fidelity_latex(numbers), encoding="utf-8")
    return target
